### ISSUE TITLE
[request] add icon for odin 

### ISSUE THREAD

**Issue by arztareef** [vyfor/icons#3]
I would really appreciate it if there were a icon image present for odin programming language.

**Comment by vyfor** [comment]
I noticed that the Ø is white while the background is blue.
![image](https://github.com/user-attachments/assets/2daf4b4c-4a5f-4e20-8ab2-9dcaeda9de70)

So here are my icon proposals:

`onyx`:
<img src="https://github.com/user-attachments/assets/3562f459-abc8-4409-9bad-6f80414817e1" width="128px">
<img src="https://github.com/user-attachments/assets/abd00ead-eb08-496b-8d01-3b8475bd7204" width="128px">

`pastel`:
<img src="https://github.com/user-attachments/assets/85969244-2beb-4f84-a654-675e17ce5e1f" width="128px">
<img src="https://github.com/user-attachments/assets/440b1b05-ef94-4b7f-9245-208efde22dac" width="128px">
