### ISSUE TITLE
 change icon for css into the new css icon 

### ISSUE THREAD

**Issue by arztareef** [vyfor/icons#4]
Recently, CSS had a update on changing few things, one of them was changing its famous blue icon to one with rebeccapurple (related with the name of the language's advocate and pioneer Eric Meyer). The icon displayed for css isn't correct and therefore, should be fixed:

![image](https://github.com/user-attachments/assets/118730f9-86b8-44dc-ac17-f587f75d83f8)
https://en.wikipedia.org/wiki/File:Official_CSS_Logo.svg

**Comment by vyfor** [comment]
Icon proposals:

`onyx`:
<img src="https://github.com/user-attachments/assets/993bdac3-036a-4a6b-ad14-3b8cf56c96c1" width="128px">

`pastel`:
<img src="https://github.com/user-attachments/assets/b8ae4cf4-2f97-468a-a2d6-d70f2d51feab" width="128px">
^ imo, the one on a darker background looks better, especially with the cutout. I will modify JavaScript & TypeScript pastel logos to also have a cutout if you like this one.

<img src="https://github.com/user-attachments/assets/888c920b-99f5-4493-aec0-726166dc3a06" width="128px">
